### ISSUE TITLE
Thumbnails are no longer being created for images added to galleries

### ISSUE THREAD

**Issue by Rainbow-Brite** [vanokhin/shortcodes-ultimate#106]
Older galleries on my site still look normal and uniform. But, when I add new images to them, the uniformity disappears because thumbnails are not being created for the new images.

1. Upload an image to WP's Media Library
2. Get the image's ID number from the URL in the Media Library
3. Copy/paste the ID number into the desired gallery
4. Preview or Update page - gallery now looks wonky and non-uniform
5. On older photos, you can right-click on the small gallery image, choose "Open image in new tab," and it will show a cropped thumbnail of the original image with constrained dimensions at the end of the URL (for instance Image12-160x160.jpg) - the same dimensions coded into the gallery - width="160" height="160"
6. On a newly-added photo, if you right-click and choose "Open image in new tab" it opens the full-res version of the image

Screenshot of an affected gallery. The two red images in the upper left are the newly added photos that are mucking up the gallery.
![image](https://user-images.githubusercontent.com/39810299/77807875-990a1400-705f-11ea-9f21-fcc3f76255c3.png)

Shortcodes Ultimate plugin has been updated to the latest version. Please help!

**Comment by vanokhin** [comment]
Hi @Rainbow-Brite,

I'm aware of this issue and going to fix it in the closest future (2-4 releases). Unfortunately, this is happening occasionally on some sites and I don't know how to fix it quickly, that's why I'm working on a new version of the shortcode.

Currently, I'd recommend you to try another plugin for galleries.

Thank you for the report and patience, and sorry for the inconvenience.
